[Settings]


[Design]
; Left or Right side of the screen?
Position=Right
; How wide should the sidebar be?
Width=48
; Background color (Hex code without the #)
BackgroundColor=141414
; Gap from the top of the screen (in case you use a top bar, I USE YASB)
TopOffset=34